services:

  mysql:
    image: mysql:8
    container_name: pos-mysql

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USERNAME} -p${DB_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    image: pos-backend:latest
    container_name: pos-backend

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql-data:
